#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-0 -d 11 12 13 14 15 16 17 18 19 20

xrandr --output DP-0 --primary --mode 1920x1080 --rate 165 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --right-of DP-0

bspc config border_width         3
bspc config window_gap          12
bspc config focused_border_color "#AF40FF"

bspc config split_ratio          0.62
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop=12
bspc rule -a thunderbird desktop=11
bspc rule -a obsidian desktop=4
bspc rule -a signal-desktop desktop=2

greenclip daemon &
nitrogen --restore

$HOME/.config/polybar/launch.sh
ckb-next -b &
syncthing -no-browser &
nvidia-settings --load-config-only &
picom --config $HOME/.config/picom/picom_anim.conf &
$HOME/.config/.scripts/startapps.sh
fcitx &
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
